import pandas as pd
from tabulate import tabulate

def run_backtest(df, initial_balance=1000):
    """
    Simulates trades based on signals generated by the strategy.
    It uses 100% of the current balance for each trade (no leverage).
    """
    balance = initial_balance
    position = None 
    trades = []
    
    for i in range(len(df)):
        row = df.iloc[i]
        
        # 1. Manage existing open position
        if position is not None:
            exit_price = None
            exit_reason = ""
            
            # Check for SL or TP hits during this candle
            if position['type'] == 1: # LONG
                # In backtesting, if both SL and TP are hit in same candle, we conservatively assume SL hit first.
                if row['low'] <= position['sl']:
                    exit_price = position['sl']
                    exit_reason = "SL"
                elif row['high'] >= position['tp']:
                    exit_price = position['tp']
                    exit_reason = "TP"
            
            elif position['type'] == -1: # SHORT
                if row['high'] >= position['sl']:
                    exit_price = position['sl']
                    exit_reason = "SL"
                elif row['low'] <= position['tp']:
                    exit_price = position['tp']
                    exit_reason = "TP"
                    
            # If position was closed
            if exit_price is not None:
                # Calculate PnL percentage (minus dummy 0.04% exchange fee for accuracy)
                fee = 0.0004
                if position['type'] == 1:
                    pnl_percent = ((exit_price - position['entry']) / position['entry']) - (fee * 2)
                else:
                    pnl_percent = ((position['entry'] - exit_price) / position['entry']) - (fee * 2)
                    
                pnl = position['invested'] * pnl_percent
                balance += pnl
                
                trades.append({
                    'entry_time': position['time'],
                    'exit_time': row['timestamp'],
                    'type': 'LONG' if position['type'] == 1 else 'SHORT',
                    'pattern': position['pattern'],
                    'entry_price': position['entry'],
                    'exit_price': exit_price,
                    'reason': exit_reason,
                    'pnl': round(pnl, 2),
                    'balance': round(balance, 2)
                })
                position = None
                
        # 2. Check for new entry (only if no open position)
        if position is None:
            if row['signal'] != 0:
                # Open position
                position = {
                    'type': row['signal'],
                    'entry': row['entry_price'],
                    'sl': row['stop_loss'],
                    'tp': row['take_profit'],
                    'time': row['timestamp'],
                    'pattern': row['pattern'],
                    'invested': balance # Trade with full current balance
                }
                
    return trades, balance

def print_report(trades, initial_balance, final_balance):
    print(f"\n{'='*40}")
    print(f"        WYCKOFF BACKTEST REPORT")
    print(f"{'='*40}")
    print(f"Initial Balance: ${initial_balance}")
    print(f"Final Balance:   ${final_balance:.2f}")
    
    net_profit = final_balance - initial_balance
    print(f"Net Profit:      ${net_profit:.2f} ({(net_profit/initial_balance)*100:.2f}%)")
    
    if len(trades) == 0:
        print("No trades executed.")
        return
        
    wins = [t for t in trades if t['pnl'] > 0]
    losses = [t for t in trades if t['pnl'] <= 0]
    win_rate = len(wins) / len(trades) * 100
    
    longs = [t for t in trades if t['type'] == 'LONG']
    long_wins = [t for t in longs if t['pnl'] > 0]
    long_win_rate = (len(long_wins) / len(longs) * 100) if len(longs) > 0 else 0
    
    shorts = [t for t in trades if t['type'] == 'SHORT']
    short_wins = [t for t in shorts if t['pnl'] > 0]
    short_win_rate = (len(short_wins) / len(shorts) * 100) if len(shorts) > 0 else 0
    
    avg_win = sum([t['pnl'] for t in wins]) / len(wins) if len(wins) > 0 else 0
    avg_loss = sum([abs(t['pnl']) for t in losses]) / len(losses) if len(losses) > 0 else 0
    rr_ratio = (avg_win / avg_loss) if avg_loss > 0 else 0

    print(f"Total Trades:    {len(trades)}")
    print(f"Wins:            {len(wins)}")
    print(f"Losses:          {len(losses)}")
    print(f"Win Rate:        {win_rate:.2f}%")
    print(f"Avg Win:         ${avg_win:.2f}")
    print(f"Avg Loss:        ${avg_loss:.2f}")
    print(f"Risk/Reward (RR): {rr_ratio:.2f}\n")
    
    print(f"--- LONG STATS ---")
    print(f"Total Longs:     {len(longs)}")
    print(f"Long Wins:       {len(long_wins)}")
    print(f"Long Win Rate:   {long_win_rate:.2f}%\n")
    
    print(f"--- SHORT STATS ---")
    print(f"Total Shorts:    {len(shorts)}")
    print(f"Short Wins:      {len(short_wins)}")
    print(f"Short Win Rate:  {short_win_rate:.2f}%\n")
    
    # Print Trades Table
    headers = ["Entry Time", "Exit Time", "Type", "Pattern", "Entry $", "Exit $", "Close", "PnL $", "Balance $"]
    rows = [[t['entry_time'], t['exit_time'], t['type'], t['pattern'], 
             round(t['entry_price'], 2), round(t['exit_price'], 2), 
             t['reason'], t['pnl'], t['balance']] for t in trades]
             
    print(tabulate(rows, headers=headers, tablefmt="grid"))
