import pandas as pd
from tabulate import tabulate

def run_backtest(df, initial_balance=1000, leverage=2, min_rr=0.1, compounding=False):
    """
    Simulates trades based on signals generated by the strategy.
    Uses leverage to maximize profit, and filters out bad RR trades.
    """
    balance = initial_balance
    position = None 
    trades = []
    
    for i in range(len(df)):
        row = df.iloc[i]
        
        # 1. Manage existing open position
        if position is not None:
            exit_price = None
            exit_reason = ""
            
            # Check for SL or TP hits during this candle
            if position['type'] == 1: # LONG
                # In backtesting, if both SL and TP are hit in same candle, we conservatively assume SL hit first.
                if row['low'] <= position['sl']:
                    exit_price = position['sl']
                    exit_reason = "SL"
                elif row['high'] >= position['tp']:
                    exit_price = position['tp']
                    exit_reason = "TP"
            
            elif position['type'] == -1: # SHORT
                if row['high'] >= position['sl']:
                    exit_price = position['sl']
                    exit_reason = "SL"
                elif row['low'] <= position['tp']:
                    exit_price = position['tp']
                    exit_reason = "TP"
                    
            # If position was closed
            if exit_price is not None:
                # Calculate PnL percentage (minus dummy 0.04% exchange fee for accuracy)
                fee = 0.0004
                if position['type'] == 1:
                    pnl_percent = ((exit_price - position['entry']) / position['entry']) - (fee * 2)
                else:
                    pnl_percent = ((position['entry'] - exit_price) / position['entry']) - (fee * 2)
                    
                pnl = position['invested'] * pnl_percent
                balance += pnl
                
                trades.append({
                    'entry_time': position['time'],
                    'exit_time': row['timestamp'],
                    'type': 'LONG' if position['type'] == 1 else 'SHORT',
                    'pattern': position['pattern'],
                    'entry_price': position['entry'],
                    'exit_price': exit_price,
                    'reason': exit_reason,
                    'pnl': round(pnl, 2),
                    'balance': round(balance, 2)
                })
                position = None
                
        # 2. Check for new entry (only if no open position)
        if position is None:
            if row['signal'] != 0:
                entry = row['entry_price']
                sl = row['stop_loss']
                tp = row['take_profit']
                
                # Check RR
                dist_sl = abs(entry - sl)
                dist_tp = abs(entry - tp)
                if dist_sl == 0: continue
                rr = dist_tp / dist_sl
                
                if rr >= min_rr:
                    # Open position
                    trade_capital = balance * leverage if compounding else initial_balance * leverage
                    position = {
                        'type': row['signal'],
                        'entry': entry,
                        'sl': sl,
                        'tp': tp,
                        'time': row['timestamp'],
                        'pattern': row['pattern'],
                        'invested': trade_capital
                    }
                
    return trades, balance

def print_report(trades, initial_balance, final_balance):
    max_bal = max([initial_balance] + [t['balance'] for t in trades]) if trades else initial_balance
    
    print(f"\n{'='*40}")
    print(f"        WYCKOFF BACKTEST REPORT")
    print(f"{'='*40}")
    print(f"Initial Balance: ${initial_balance}")
    print(f"Peak Balance:    ${max_bal:.2f}")
    print(f"Final Balance:   ${final_balance:.2f}")
    
    net_profit = final_balance - initial_balance
    print(f"Net Profit:      ${net_profit:.2f} ({(net_profit/initial_balance)*100:.2f}%)")
    
    if len(trades) == 0:
        print("No trades executed.")
        return
        
    wins = [t for t in trades if t['pnl'] > 0]
    losses = [t for t in trades if t['pnl'] <= 0]
    win_rate = len(wins) / len(trades) * 100
    
    longs = [t for t in trades if t['type'] == 'LONG']
    long_wins = [t for t in longs if t['pnl'] > 0]
    long_win_rate = (len(long_wins) / len(longs) * 100) if len(longs) > 0 else 0
    
    shorts = [t for t in trades if t['type'] == 'SHORT']
    short_wins = [t for t in shorts if t['pnl'] > 0]
    short_win_rate = (len(short_wins) / len(shorts) * 100) if len(shorts) > 0 else 0
    
    avg_win = sum([t['pnl'] for t in wins]) / len(wins) if len(wins) > 0 else 0
    avg_loss = sum([abs(t['pnl']) for t in losses]) / len(losses) if len(losses) > 0 else 0
    rr_ratio = (avg_win / avg_loss) if avg_loss > 0 else 0

    max_balance = initial_balance
    max_dd_percent = 0.0
    max_dd_usd = 0.0
    current_streak = 0
    max_losing_streak = 0
    worst_trade_usd = 0.0
    
    for t in trades:
        # Max Drawdown
        if t['balance'] > max_balance:
            max_balance = t['balance']
        dd_usd = max_balance - t['balance']
        dd_percent = (dd_usd / max_balance) * 100 if max_balance > 0 else 0
        if dd_percent > max_dd_percent:
            max_dd_percent = dd_percent
            max_dd_usd = dd_usd
            
        # Losing Streak
        if t['pnl'] <= 0:
            current_streak += 1
            if current_streak > max_losing_streak:
                max_losing_streak = current_streak
        else:
            current_streak = 0
            
        # Worst Trade
        if t['pnl'] < worst_trade_usd:
            worst_trade_usd = t['pnl']

    print(f"Total Trades:    {len(trades)}")
    print(f"Wins:            {len(wins)}")
    print(f"Losses:          {len(losses)}")
    print(f"Win Rate:        {win_rate:.2f}%")
    print(f"Avg Win:         ${avg_win:.2f}")
    print(f"Avg Loss:        ${avg_loss:.2f}")
    print(f"Risk/Reward (RR): {rr_ratio:.2f}")
    print(f"Max Drawdown:    ${max_dd_usd:.2f} ({max_dd_percent:.2f}%)")
    print(f"Longest Loss Strk: {max_losing_streak}")
    print(f"Worst Trade:     ${worst_trade_usd:.2f}\n")
    
    print(f"--- LONG STATS ---")
    print(f"Total Longs:     {len(longs)}")
    print(f"Long Wins:       {len(long_wins)}")
    print(f"Long Win Rate:   {long_win_rate:.2f}%\n")
    
    print(f"--- SHORT STATS ---")
    print(f"Total Shorts:    {len(shorts)}")
    print(f"Short Wins:      {len(short_wins)}")
    print(f"Short Win Rate:  {short_win_rate:.2f}%\n")

    print(f"--- YEARLY PNL ---")
    yearly_pnl = {}
    current_year = None
    
    for t in trades:
        year_str = t['exit_time'].strftime('%Y')
        if current_year != year_str:
            if current_year is not None:
                yearly_pnl[current_year]['end_bal'] = t['balance'] - t['pnl']
                
            current_year = year_str
            yearly_pnl[current_year] = {
                'start_bal': t['balance'] - t['pnl'],
                'pnl_usd': 0.0,
                'end_bal': t['balance']
            }
            
        yearly_pnl[current_year]['pnl_usd'] += t['pnl']
        yearly_pnl[current_year]['end_bal'] = t['balance']
        
    for y in sorted(yearly_pnl.keys()):
        start_b = yearly_pnl[y]['start_bal']
        pnl_usd = yearly_pnl[y]['pnl_usd']
        pct_growth = (pnl_usd / start_b * 100) if start_b > 0 else 0
        print(f"{y}: ${pnl_usd:,.2f} ({pct_growth:+.2f}%)")

    unique_months = set([t['exit_time'].strftime('%Y-%m') for t in trades])
    num_months = len(unique_months) if len(unique_months) > 0 else 1
    total_pct = (final_balance - initial_balance) / initial_balance * 100
    avg_monthly_pct = total_pct / num_months
    
    print(f"\nAvg Monthly Profit: {avg_monthly_pct:+.2f}% (over {num_months} active months)")
